variables:
  STORAGE_DRIVER: vfs

before_script:
  - echo "$DOCKER_HUB_PASSWORD" | buildah login -u devlandserviceworker --password-stdin

stages:
  - build
  - test
  - package

Build:
  stage: build
  image: golang:latest
  script:
    - go build

Container:
  stage: package
  image: quay.io/buildah/stable
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - buildah login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - buildah bud -t $IMAGE_NAME
    - CONTAINER_ID=$(buildah from ${IMAGE_NAME})
    - buildah commit --squash $CONTAINER_ID $IMAGE_NAME
    - buildah push $IMAGE_NAME

Test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  script:
    - turtle
