image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u devlandserviceworker --password-stdin

stages:
  - build

joshgrancell.com:
  stage: build
  script:
    - docker build --tag jgrancell/turtleshell:latest --tag jgrancell/turtleshell:$CI_BUILD_REF .
    - docker push jgrancell/turtleshell:$CI_BUILD_REF
    - docker push jgrancell/turtleshell:latest
